version: '3.4'

networks:
  dockerapi-dev:
    driver: bridge

services:
  webapiparser.api:
    image: ${DOCKER_REGISTRY-}webapiparser
    container_name: WebApiParser
    build:
      context: .
      dockerfile: WebApiParser/Dockerfile
    environment:
      ConnectionStrings__DefaultConnection: "host=sql;port=5432;database=WebApiParser;username=postgres;password=password"
      Logging__LogLevel__Default: "Error"
    ports:
      - "5101:80"
    networks:
      - dockerapi-dev
  sql:
    image: postgres:latest
    container_name: sql
    ports:
      - "5433:5432"
    restart: always
    volumes:
      - webapiparser_db_volume:/var/lib/postrgesql/data
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "WebApiParser"
    networks:
      - dockerapi-dev

  mongodb:
     image: mongo:4.4
     networks:
        - dockerapi-dev
     volumes:
      - /mongo_data:/data/db

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
    volumes:
      - /es_data:/usr/share/elasticsearch/data
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    networks:
      - dockerapi-dev

  graylog:
    image: graylog/graylog:4.2
    volumes:
      - /graylog_journal:/usr/share/graylog/data/journal
    environment:
      - GRAYLOG_PASSWORD_SECRET=somepasswordpepper
        # Password: admin
      - GRAYLOG_ROOT_PASSWORD_SHA2=e1b24204830484d635d744e849441b793a6f7e1032ea1eef40747d95d30da592
      - GRAYLOG_HTTP_EXTERNAL_URI=http://localhost:9000/
    entrypoint: /usr/bin/tini -- wait-for-it elasticsearch:9200 --  /docker-entrypoint.sh
    ports:
      # Graylog web interface and REST API
      - 9000:9000
      # Syslog TCP
      - 1514:1514
      # Syslog UDP
      - 1514:1514/udp
      # GELF TCP
      - 12201:12201
      # GELF UDP
      - 12201:12201/udp
    links:
      - mongodb:mongo
      - elasticsearch
    restart: always
    depends_on:
      - mongodb
      - elasticsearch
    networks:
      - dockerapi-dev

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    networks:
      - dockerapi-dev

volumes:
  mongo_data:
    driver: local
  es_data:
    driver: local
  graylog_journal:
    driver: local
  webapiparser_db_volume: